// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfgvsnmmezdypyjcpdof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmZ3Zzbm1tZXpkeXB5amNwZG9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MjQ4NTcsImV4cCI6MjA2OTUwMDg1N30.9v4fKAkT_dbkqILQeIvWf1SMk61-QfLRcbKhsib-IgQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});